baseURL = "https://www.rent-a-dev-team.de/"
languageCode = "de_DE"
title = "Meghna"
# theme = "meghna-hugo"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# default content language
defaultContentLanguage = "de"
defaultContentLanguageInSubdir = false
# disable language
disableLanguages = [""]

############################# Plugins ##########################
# css plugins
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
URL = "plugins/animate-css/animate.css"
[[params.plugins.css]]
URL = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "css/custom.css"

# js plugins
[[params.plugins.js]]
URL = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
URL = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
URL = "plugins/wow/wow.min.js"
[[params.plugins.js]]
URL = "plugins/jquery-ui/jquery-ui.min.js"

[taxonomies]
  author = "author"
  category = "categories"
  tag = "tags"
############################# Navigation ##################################
[menu]

  [[menu.main]]
  name = "Ihr Problem"
  URL = "situation"
  weight = 1

  [[menu.main]]
  name = "Lösung"
  URL = "solution"
  weight = 2

  [[menu.main]]
  name = "Werte"
  URL = "values-and-vision"
  weight = 3

  [[menu.main]]
  name = "Portfolio"
  URL = "portfolio"
  weight = 4

  [[menu.main]]
  name = "Team"
  URL = "team"
  weight = 5


############################# Default Parameters ##########################
[params]
logo = "images/logo.png"
# Meta data
description = "Responsive Multipurpose Parallax HTML5 Template"
author = "Nils Bokermann"
# Google Analitycs
googleAnalitycsID = "Your ID"
# post share
postShare = true

# preloader
[params.preloader]
enable = false
preloader = "images/preload.jpg"

############################# social icons ##########################
#[[params.social_Icon]]
#icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
#link = "#"

#[[params.social_Icon]]
#icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
#link = "#"

#[[params.social_Icon]]
#icon = "ti-youtube" # themify icon pack : https://themify.me/themify-icons
#link = "#"

#[[params.social_Icon]]
#icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
#link = "#"

#[[params.social_Icon]]
#icon = "ti-dribbble" # themify icon pack : https://themify.me/themify-icons
#link = "#"

[[params.social_Icon]]
icon = "ti-pinterest" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.link_Footer]]
link = "impressum"
text = "Impressum"

################################# language ################################
[Languages]

  ################################ English Language ########################
  [Languages.de]
  languageName = "De"
  languageCode = "de-de"
  contentDir = "content/"
  weight = 1
  home = ""
